[CmdletBinding()]
param(
    [Parameter()]
    [string] $OutputDirectory = '.\requirements\vb\behavior'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$requirements = @(
    [ordered]@{ id=106; group='Forms'; slug='form-instance-lifecycle'; title='Form instance and load lifecycle'; applies='`Form` and `MDIForm`'; text='WFC shall create a form instance before its first executable event, raise `Initialize` once for each instance, load persisted controls and properties before `Load`, raise `Load` once per load cycle, and make the default form instance available through its class name. Referencing a property or invoking `Show` on an unloaded default instance shall load it. Re-entrant references during initialization or loading shall resolve to the same instance.'; verify='Record object identity and the ordered trace produced by explicit `Load`, implicit property access, `Show`, repeated `Load`, and a re-entrant reference from `Initialize` and `Load`.' },
    [ordered]@{ id=107; group='Forms'; slug='form-visibility-modality'; title='Form visibility, ownership, and modality'; applies='`Form` and `MDIForm`'; text='`Load` shall create a form without requiring it to be visible; `Show` shall load an unloaded form and make it visible; `Hide` shall remove it from display without unloading it or discarding state. Modal `Show` shall suspend the calling VB execution path until the form is hidden or unloaded, disable the applicable owner window while modal, and restore owner activation when the modal operation ends. Modeless and owned-form behavior shall follow the reference result for each accepted `Modal` and `OwnerForm` argument.'; verify='Trace visibility, state retention, caller blocking, owner enabled/active state, nesting, and invalid modal/owner arguments for loaded and unloaded forms.' },
    [ordered]@{ id=108; group='Forms'; slug='form-unload-termination'; title='Form query, unload, and termination'; applies='`Form` and `MDIForm`'; text='An ordinary close or `Unload` operation shall raise `QueryUnload` before `Unload`, populate `UnloadMode` with the reference reason, and honor each `Cancel` argument at the stage where VB6 permits cancellation. Successful unloading shall destroy the window and loaded controls while preserving any independently held form-object reference as in VB6. `Terminate` shall occur only when the form object is finally released. Abrupt `End` termination is outside this orderly event path.'; verify='Close forms by control menu, code, owner/MDI shutdown, task-manager/session shutdown where safely reproducible, and application exit; cancel each event separately and trace window, object, and event lifetime.' },
    [ordered]@{ id=109; group='Forms'; slug='activation-focus-validation'; title='Activation, focus, validation, and key preview'; applies='`Form`, `MDIForm`, and focusable intrinsic controls'; text='WFC shall track one active form and one active control per applicable container, raise activation/deactivation and focus events when those states change, and expose them through `ActiveForm` and `ActiveControl`. Before focus leaves a control, WFC shall raise `Validate(Cancel)` when the destination causes validation; cancellation shall retain focus and suppress the remaining transition as in VB6. A form with `KeyPreview = True` shall receive keyboard events before the focused control, with ByRef key mutations affecting subsequent dispatch.'; verify='Trace keyboard, mouse, `SetFocus`, hide, disable, unload, and cross-form transitions with validation accepted, cancelled, and bypassed by `CausesValidation = False`; mutate `KeyCode` and `KeyAscii` in form handlers.' },
    [ordered]@{ id=110; group='Forms'; slug='form-window-mdi'; title='Form window geometry, state, and MDI behavior'; applies='`Form` and `MDIForm`'; text='WFC shall apply border, control-box, minimize/maximize, taskbar, startup-position, moveability, window-state, icon, caption, and geometry properties with VB6 design-time versus run-time mutability. Geometry and window-state transitions shall raise `Resize` in the reference cases. An `MDIForm` shall contain MDI-child forms, maintain `ActiveForm`, arrange children, implement `AutoShowChildren` and scroll-bar behavior, and constrain MDI-child visibility, ownership, and activation as the reference does.'; verify='Exercise every border and startup style, minimize/maximize/restore, programmatic and interactive moves, taskbar presence, MDI child load/show/hide/unload, activation, arranging, scrolling, and invalid MDI configurations.' },
    [ordered]@{ id=111; group='Forms'; slug='containment-control-arrays'; title='Control containment, lookup, and control arrays'; applies='Form hosts, container controls, and all intrinsic controls exposing `Index`'; text='WFC shall preserve the design-time containment hierarchy exposed through `Parent`, `Container`, `Controls`, `Count`, and the form default member. Controls shall be retrievable using the VB6-supported name and index forms. Controls sharing a name and distinct `Index` values shall behave as a control array: event dispatch shall identify the originating index, `Load` shall create a new run-time element using reference property-copy and visibility rules, and `Unload` shall remove only elements eligible for dynamic removal while preserving index bounds and lookup errors.'; verify='Build nested frames and picture boxes, enumerate and index controls, test duplicate names and sparse indices, dynamically load/show/unload array elements, compare copied properties and tab order, and record invalid lookup/removal errors.' },
    [ordered]@{ id=112; group='Common control behavior'; slug='common-control-state'; title='Common intrinsic-control state and interaction'; applies='All visual intrinsic controls'; text='Each intrinsic control shall apply `Enabled`, `Visible`, position, size, `TabIndex`, `TabStop`, mouse-pointer/icon, tooltip, help context, font, color, appearance, right-to-left, tag, and container properties where its API exposes them. `Move`, `ZOrder`, `Refresh`, `SetFocus`, and mouse, keyboard, click, double-click, drag, and focus events shall match VB6 availability, ordering, coordinate units, ByRef mutation, and error behavior. Disabling or hiding a focused control shall transfer focus as in the reference.'; verify='Use a matrix across every visual intrinsic class for property defaults and mutation, tab navigation, focus eligibility, z-order, refresh, input event order, coordinate values, ByRef cancellation, visibility, disabled input, and invalid values.' },
    [ordered]@{ id=113; group='Forms'; slug='coordinates-drawing'; title='Form and PictureBox coordinate and drawing behavior'; applies='`Form` and `PictureBox`'; text='WFC shall implement VB6 logical coordinate systems through `ScaleMode`, `ScaleLeft`, `ScaleTop`, `ScaleWidth`, `ScaleHeight`, `Scale`, `ScaleX`, and `ScaleY`. Drawing state and operations including current position, colors, modes, styles, widths, fills, `AutoRedraw`, `ClipControls`, `Cls`, `Circle`, `Line`, `PaintPicture`, `Point`, `PSet`, text measurement, `Image`, `Picture`, `hDC`, `HasDC`, `Paint`, and `PrintForm` shall produce reference-equivalent pixels, units, persistence, repainting, and errors.'; verify='Render deterministic fixtures under every supported scale and draw mode to retained bitmaps; cover negative dimensions, clipping, resize/repaint, AutoRedraw on/off, image/picture snapshots, text metrics, device-context lifetime, and invalid arguments.' },
    [ordered]@{ id=114; group='Common control behavior'; slug='drag-drop'; title='Manual and OLE drag-and-drop behavior'; applies='Forms and intrinsic controls exposing drag or OLE drag/drop members'; text='WFC shall implement manual drag states and `DragDrop`/`DragOver` event transitions, plus OLE drag initiation, format negotiation, delayed data supply, effects, feedback, completion, and drop events. ByRef `Effect`, `State`, and cursor-selection values shall control subsequent behavior; disabled OLE modes shall reject the corresponding operation. Coordinates and source/data object identity shall match VB6.'; verify='Trace enter/over/leave/drop and cancel sequences within and across controls and processes, negotiate text and binary formats, request delayed data, vary allowed effects and ByRef mutations, and compare cursors, coordinates, event order, and errors.' },
    [ordered]@{ id=115; group='Forms'; slug='form-control-persistence'; title='Form and intrinsic-control persistence'; applies='Forms, menus, and intrinsic controls'; text='WFC shall load the VB6 form description and companion binary resources needed to reconstruct form class identity, containment, control arrays, menus, design-time property values, fonts, colors, pictures, icons, and persisted control state. Properties omitted from source shall assume VB6 defaults. Unknown, malformed, versioned, or unsupported persisted values shall produce a controlled compatibility diagnostic rather than silent reinterpretation.'; verify='Save representative VB6 projects containing every form and intrinsic-control class, compare text and binary resource reconstruction, omit default properties, vary locale and line endings, and exercise malformed and unsupported records.' },
    [ordered]@{ id=116; group='Intrinsic controls'; slug='picture-box'; title='PictureBox container and presentation behavior'; applies='`PictureBox`'; text='`PictureBox` shall act as a visual control and container, preserve child coordinates and clipping, display its `Picture`, produce its composed `Image`, apply `AutoSize`, border and appearance styles, and implement the drawing contract in REQ-0113. Picture mutation, resizing, repainting, data binding, and DDE/OLE interactions shall raise the reference events and retain pixels according to `AutoRedraw`.'; verify='Compare containment, clipping, autosize, picture versus image identity, bitmap/icon/metafile rendering, resize and paint traces, data changes, and drawing persistence.' },
    [ordered]@{ id=117; group='Intrinsic controls'; slug='label'; title='Label caption and mnemonic behavior'; applies='`Label`'; text='`Label` shall render its caption using the configured alignment, font, foreground/background, border, appearance, `BackStyle`, right-to-left, `AutoSize`, and `WordWrap` behavior. With `UseMnemonic` enabled, an ampersand mnemonic shall be displayed and route keyboard focus to the next eligible control according to VB6 tab order; escaped ampersands shall render literally. Caption changes shall update layout and raise `Change` as in VB6.'; verify='Compare raster output and geometry for empty, multiline, long, mnemonic, escaped-ampersand, right-to-left, transparent, autosized, wrapped, bordered, and disabled labels; trace Change and mnemonic focus.' },
    [ordered]@{ id=118; group='Intrinsic controls'; slug='text-box'; title='TextBox editing and selection behavior'; applies='`TextBox`'; text='`TextBox` shall implement single-line and multiline editing, `Text` as its default value, `MaxLength`, `Locked`, `PasswordChar`, alignment, scrolling, selection through `SelStart`, `SelLength`, and `SelText`, and `HideSelection`. User and programmatic edits shall update text, caret, and selection and raise `Change`, keyboard, validation, and focus events in the VB6 cases and order. Invalid ranges, newline forms, clipboard commands, undo behavior, and native text limits shall match the reference profile.'; verify='Exercise typing, paste/cut/copy, selection replacement, programmatic Text and SelText changes, max length, password display, multiline newline and scrolling, locked/disabled states, focus loss, validation, Unicode/ANSI conversion, and invalid indices.' },
    [ordered]@{ id=119; group='Intrinsic controls'; slug='frame'; title='Frame containment and option grouping'; applies='`Frame`'; text='`Frame` shall provide a visual and functional child-control container with VB6 clipping, coordinates, enabled/visible propagation, caption, border, appearance, and input behavior. Option buttons whose immediate container is the same frame shall form a mutually exclusive group independent of option buttons in other containers. Moving an existing control over a frame shall not change containment unless the VB6 designer/source representation does so.'; verify='Compare nested containment, child coordinates, clipping, enable/visible interaction, z-order, hit testing, caption/border rendering, option groups across multiple frames, and design-time versus run-time placement.' },
    [ordered]@{ id=120; group='Intrinsic controls'; slug='command-button'; title='CommandButton activation behavior'; applies='`CommandButton`'; text='`CommandButton` shall raise `Click` for reference-equivalent mouse, keyboard, mnemonic, programmatic `Value`, default-button Enter, and cancel-button Escape activation. Exactly the eligible `Default` and `Cancel` command buttons for the active form shall receive those keys. Standard and graphical styles shall apply normal, disabled, and down pictures, mask color, caption, focus cue, and pressed state as in VB6. `CausesValidation` shall govern pre-click validation.'; verify='Activate by every input path with focus on different controls, accepted/cancelled validation, enabled/visible changes, multiple default/cancel assignments, and all graphical pictures/masks; compare event count/order and pixels.' },
    [ordered]@{ id=121; group='Intrinsic controls'; slug='selection-buttons'; title='CheckBox and OptionButton selection behavior'; applies='`CheckBox` and `OptionButton`'; text='`CheckBox.Value` shall implement unchecked, checked, and grayed values where allowed, with user interaction cycling only through the reference states and raising `Click` as in VB6. Selecting an `OptionButton` shall set its `Value` true and clear the other option buttons in the same immediate container group without affecting other containers. Programmatic assignments, keyboard/mnemonic activation, alignment, graphical styles, pictures, masks, validation, and data binding shall match the reference.'; verify='Exercise every value by code and input, invalid values, click/event behavior, keyboard and mnemonics, multiple containers, initial multiple-true persistence, dynamic control arrays, graphical rendering, validation, and bound values.' },
    [ordered]@{ id=122; group='Intrinsic controls'; slug='list-combo'; title='ListBox and ComboBox item and selection behavior'; applies='`ListBox` and `ComboBox`'; text='The controls shall maintain zero-based `List` and `ItemData` entries, `ListCount`, `ListIndex`, `Text`, `NewIndex`, and `TopIndex`; implement `AddItem`, indexed insertion, `RemoveItem`, and `Clear`; and apply `Sorted`, columns, integral-height, and style rules. `ListBox` shall implement single, simple-multiple, extended-multiple, `Selected`, `SelCount`, and checkbox-item behavior. `ComboBox` shall implement simple, drop-down editable, and drop-down-list behavior including text selection, `Locked`, drop-down, change, click, scroll, and validation events.'; verify='Mutate empty and populated lists at all indices; test duplicates, sorting and NewIndex, item data, selection modes, keyboard/mouse range selection, checked items, top index, columns, every combo style, text editing, events, limits, and invalid indices.' },
    [ordered]@{ id=123; group='Intrinsic controls'; slug='scroll-bars'; title='Horizontal and vertical ScrollBar behavior'; applies='`HScrollBar` and `VScrollBar`'; text='Each scroll bar shall constrain `Value` to the inclusive `Min`/`Max` range, support reference reversed-range behavior, and apply `SmallChange` and `LargeChange` for arrow, keyboard, page, and track interactions. Interactive tracking shall raise `Scroll` and committed value changes shall raise `Change` in the VB6 order and frequency. Programmatic assignments, focus, keyboard direction, right-to-left behavior, range mutation, and invalid values shall match VB6.'; verify='Cover normal, equal, and reversed ranges; boundary clamping/errors; programmatic and every input path; held/repeated input; live thumb tracking; event order/count; focus; disable/hide; and right-to-left layout.' },
    [ordered]@{ id=124; group='Intrinsic controls'; slug='timer'; title='Timer scheduling behavior'; applies='`Timer`'; text='An enabled `Timer` with a nonzero valid `Interval` shall raise `Timer` events on its owning UI thread according to VB6 message-driven scheduling. `Enabled = False` or `Interval = 0` shall suppress delivery. Changing interval or enabled state, including from within the handler, shall reschedule or stop future events as in VB6. Delivery may coalesce or drift under a blocked message loop and shall not recursively overlap a running handler unless observed in the reference.'; verify='Measure event timestamps and thread identity across boundary intervals, disabled/zero states, handler overruns, blocked message loops, modal forms, property changes inside handlers, unload, and system timer granularity.' },
    [ordered]@{ id=125; group='Intrinsic controls'; slug='lightweight-graphics'; title='Image, Shape, and Line presentation behavior'; applies='`Image`, `Shape`, and `Line`'; text='The lightweight graphical controls shall render without independent window handles and participate in container z-order, clipping, visibility, and repainting as in VB6. `Image` shall render pictures using stretch, border, appearance, transparency, input, drag/drop, and data-binding rules. `Shape` shall render every supported shape with border, fill, background, and draw modes. `Line` shall render its endpoints with border color, style, width, and draw mode, and expose bounds derived from its coordinates as VB6 does.'; verify='Inspect window handles, hit testing and overlap with windowed controls; compare bitmap/icon/metafile images with stretch on/off; render every shape, line direction, width/style/fill/draw mode, clipping and resize; trace Image input.' },
    [ordered]@{ id=126; group='Intrinsic controls'; slug='file-system-lists'; title='Drive, directory, and file list behavior'; applies='`DriveListBox`, `DirListBox`, and `FileListBox`'; text='`DriveListBox` shall enumerate reference-visible drives and update `Drive`; `DirListBox` shall normalize and enumerate `Path`; and `FileListBox` shall enumerate `Path` entries filtered by `Pattern` and the `Normal`, `ReadOnly`, `Archive`, `Hidden`, and `System` attributes. Their list, selection, scrolling, refresh, and change/path/pattern events shall match VB6. The controls shall not invent automatic cross-control synchronization beyond behavior observed when client event code assigns the related properties.'; verify='Use a controlled filesystem fixture and available drive types; test relative, absolute, root, UNC, missing, inaccessible, long, ANSI, and mixed-case paths; multiple patterns and attributes; refresh after mutation; selection/events; and explicit three-control synchronization.' },
    [ordered]@{ id=127; group='Intrinsic controls'; slug='menus'; title='Menu hierarchy and command behavior'; applies='`Menu` and forms containing menus'; text='WFC shall reconstruct the design-time menu hierarchy, captions, separators, access keys, shortcuts, checked, enabled, visible, tag, help context, index/control-array, and `WindowList` behavior. Menus shall participate in form layout and MDI window listing as in VB6 and raise the correct `Click` handler for mouse, keyboard, mnemonic, shortcut, and programmatic paths supported by VB6. Run-time property changes shall update native presentation and command routing.'; verify='Exercise nested menus, separators, duplicate mnemonics, shortcuts, checked/disabled/hidden states, menu control arrays, popup menus, dynamic captions, right-to-left forms, MDI window lists, and every activation path.' },
    [ordered]@{ id=128; group='Intrinsic controls'; slug='data-control'; title='Intrinsic Data control behavior'; applies='`Data` and data-bound intrinsic controls'; text='The intrinsic Data control shall implement the VB6/DAO connection, database, record-source, recordset, cursor, locking, edit, BOF/EOF action, refresh, navigation, update, and error model exposed by its API. Bound controls shall exchange values through `DataSource`, `DataMember`, `DataField`, `DataFormat`, and `DataChanged`; `UpdateControls` and `UpdateRecord` shall synchronize in the reference direction and raise `Validate`, `Reposition`, `Error`, and bound-control change events with reference cancellation and response semantics.'; verify='Use version-controlled DAO databases to test open/close, table/query/SQL sources, navigation and boundaries, add/edit/delete/update/cancel, validation and errors, nulls and conversions, formatting, multi-control binding, external record changes, read-only/exclusive modes, and teardown.' },
    [ordered]@{ id=129; group='Intrinsic controls'; slug='ole-control'; title='Intrinsic OLE container behavior'; applies='`OLE`'; text='The OLE control shall host linked and embedded OLE objects using the reference class/type restrictions, creation and paste dialogs, source document/item, activation modes, verbs, size/display modes, update policy, data formats, clipboard operations, object movement, persistence, and close/delete lifecycle. Its `Object`, `LpOleObject`, application-running state, accepted/provided formats, actions, events, and errors shall preserve COM identity, reference counting, in-place activation, and storage interoperability required by VB6 containers.'; verify='Use deterministic in-process and out-of-process OLE test servers plus installed standard servers to exercise create/link/embed, verbs, in-place activation, update, clipboard, save/load formats, movement/resize, server failure, cancellation, close/delete, reference lifetime, and invalid classes/documents.' },
    [ordered]@{ id=130; group='Common control behavior'; slug='dde-links'; title='VB6 DDE link behavior'; applies='Forms and intrinsic controls exposing `LinkTopic`, `LinkItem`, `LinkMode`, or link methods/events'; text='Where the compatibility profile includes DDE, WFC shall implement manual and automatic link establishment, request, poke, execute, notification, timeout, close, error, and form-level command execution behavior with VB6 topic/item string rules and event cancellation. Where DDE is excluded, use of these members shall fail through one documented compatibility diagnostic rather than appearing to succeed.'; verify='Use a controlled DDE client/server pair to trace cold, warm, and hot links, timeouts, reconnects, request/poke/execute data conversion, event order, cancellation, server termination, malformed topics/items, and excluded-profile behavior.' },
    [ordered]@{ id=131; group='Common control behavior'; slug='data-binding'; title='Common intrinsic-control data binding'; applies='Intrinsic controls exposing `DataSource`, `DataMember`, `DataField`, `DataFormat`, or `DataChanged`'; text='A bound intrinsic control shall resolve its data source/member/field using VB6 rules, convert between field and control value using `DataFormat` and locale, report pending edits through `DataChanged`, refresh when the current record changes, and participate in update, validation, null, error, and teardown behavior without losing reference-equivalent edits. Unsupported provider or format features shall return a stable compatibility error.'; verify='Bind each eligible control to controlled DAO and Automation sources; cover navigation, edits from both sides, null/empty/error values, conversion and locale, validation cancellation, read-only fields, source replacement/destruction, invalid member/field/format, and multiple consumers.' }
)

function Write-Requirement {
    param($Requirement, [string] $Directory)
    $id = 'REQ-{0:D4}' -f $Requirement.id
    $test = 'TC-{0:D4}' -f $Requirement.id
    $lines = @(
        "# $id — $($Requirement.title)",
        '',
        '**Content type:** Project requirement',
        '',
        '**Status:** Proposed',
        '',
        '**Source:** Installed `VB6.OLB`; VB6 form/control documentation baseline',
        '',
        '## Scope',
        '',
        "This requirement applies to $($Requirement.applies) on supported Windows targets.",
        '',
        '## Requirement',
        '',
        $Requirement.text,
        '',
        '## Rationale',
        '',
        'The VB6 type library identifies this behavior as part of the form-runtime surface;',
        'the details affect existing source, persisted forms, user interaction, or compiled',
        'application behavior and therefore require an explicit compatibility contract.',
        '',
        '## Verification',
        '',
        '**Method:** Test',
        '',
        "**References:** Planned ``$test`` VB6 reference and WFC conformance test",
        '',
        $Requirement.verify,
        '',
        'The probe shall retain inputs, event traces, values, errors, and visual evidence',
        'needed to distinguish the stated cases. WFC shall match the confirmed reference',
        'result unless an approved tailoring decision states otherwise.',
        '',
        '## Relationships',
        '',
        '- **Derived from:** `evidence/reference/vb-6.0-type-library.json` and',
        '  `evidence/reference/vb6-form-control-documentation.md`',
        '- **Depends on:** Applicable VB class API contracts in `REQ-0037` through `REQ-0068`',
        '- **Conflicts with:** None known',
        '',
        '## Tailoring',
        '',
        'A documented platform difference may be accepted only through an approved',
        'compatibility-scope or architecture decision that identifies its user impact.',
        '',
        '## Implementation Record',
        '',
        'Not implemented.'
    )
    $path = Join-Path $Directory ('req-{0:D4}-{1}.md' -f $Requirement.id, $Requirement.slug)
    [IO.File]::WriteAllLines($path, $lines, [Text.UTF8Encoding]::new($false))
}

$resolvedOutput = [IO.Path]::GetFullPath($OutputDirectory)
[IO.Directory]::CreateDirectory($resolvedOutput) | Out-Null
foreach ($requirement in $requirements) { Write-Requirement $requirement $resolvedOutput }

$index = [System.Collections.Generic.List[string]]::new()
$index.Add('# Visual Basic 6.0 Form and Intrinsic-Control Behavioral Requirements')
$index.Add('')
$index.Add('**Content type:** Project requirement index')
$index.Add('')
$index.Add('**Status:** Proposed')
$index.Add('')
$index.Add('These requirements turn the installed VB6 form/control object model into')
$index.Add('observable obligations. The core `VB98.CHM` help is not installed; the source')
$index.Add('basis and substitution policy are recorded in the retained documentation')
$index.Add('baseline. Each requirement remains Proposed until its named reference probe')
$index.Add('confirms defaults, ordering, errors, rendering, and platform-sensitive behavior.')
$index.Add('')
foreach ($group in @($requirements.group | Select-Object -Unique)) {
    $index.Add("## $group")
    $index.Add('')
    foreach ($requirement in @($requirements | Where-Object group -eq $group)) {
        $id = 'REQ-{0:D4}' -f $requirement.id
        $file = 'req-{0:D4}-{1}.md' -f $requirement.id, $requirement.slug
        $index.Add("- [$id — $($requirement.title)]($file)")
    }
    $index.Add('')
}
$index.Add('## Evidence and Acceptance')
$index.Add('')
$index.Add('The type library establishes the callable surface but does not encode event')
$index.Add('order, defaults, pixels, timing, errors, or persistence rules. A requirement')
$index.Add('becomes eligible for acceptance only after its planned `TC-NNNN` probe records')
$index.Add('the installed VB6 behavior and verifies WFC against the resulting expectation.')
[IO.File]::WriteAllLines((Join-Path $resolvedOutput 'README.md'), $index, [Text.UTF8Encoding]::new($false))
